FROM ghcr.io/onedr0p/whisparr-nightly:0.1.0.53@sha256:5a6ce55522afa84195cd723447f987f63a19009a37e2779b861a65aec940572b
LABEL org.opencontainers.image.source=https://github.com/bh2754/containers
ARG CONTAINER_NAME
ARG CONTAINER_VER
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
LABEL org.opencontainers.image.title="${CONTAINER_NAME}"
LABEL org.opencontainers.image.version="${CONTAINER_VER}"
LABEL org.opencontainers.image.description="Container for ${CONTAINER_NAME} by bh2754"
LABEL org.opencontainers.image.authors="bh2754"
